# Generated by Django 3.2.25 on 2026-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_add_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activo',
            field=models.SmallIntegerField(db_index=True, default=1, help_text='1 = activo, 0 = inactivo'),
        ),
    ]
